# Generated by Django 3.0 on 2025-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=450)),
                ('component_name', models.CharField(max_length=450)),
                ('short_desc', models.CharField(max_length=450)),
                ('status_category', models.CharField(max_length=100)),
                ('status_code', models.CharField(max_length=100)),
                ('bug_fix', models.CharField(max_length=100)),
                ('severity_code', models.CharField(max_length=100)),
                ('bug_severity', models.CharField(max_length=100)),
            ],
        ),
    ]
